services:
  django:
    build:
      context: ../Backend/Django
      dockerfile: Dockerfile
    image: django-backend
    env_file:
      - ./Django_env/.env
    ports:
      - "8000:8000"

  fastapi:
    build:
      context: ../Backend/FastAPI
      dockerfile: Dockerfile
    image: fastapi-backend
    env_file:
      - ./Fastapi_env/.env
    ports:
      - "8001:8001"

  react:
    build:
      context: ../Frontend
      dockerfile: Dockerfile
    image: react-frontend
    env_file:
      - ./React_env/.env
    ports:
      - "5173:5173"
  # db:
  #   image: mysql:8
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: mydb
  #   ports:
  #     - "3306:3306"
